using TeleHealth.Api.Features.Admins.CreateDepartment;
using TeleHealth.Api.Features.Admins.CreateLabTech;
using TeleHealth.Api.Features.Admins.CreateReceptionist;
using TeleHealth.Api.Features.Admins.DeleteDepartment;
using TeleHealth.Api.Features.Admins.DeleteLabTech;
using TeleHealth.Api.Features.Admins.DeleteReceptionist;
using TeleHealth.Api.Features.Admins.GetAllDepartments;
using TeleHealth.Api.Features.Admins.GetAllLabTechs;
using TeleHealth.Api.Features.Admins.GetAllReceptionists;
using TeleHealth.Api.Features.Admins.GetAuditLogs;
using TeleHealth.Api.Features.Admins.GetDashboardSummary;
using TeleHealth.Api.Features.Admins.GetLabTech;
using TeleHealth.Api.Features.Admins.GetSettings;
using TeleHealth.Api.Features.Admins.UpdateDepartment;
using TeleHealth.Api.Features.Admins.UpdateLabTech;
using TeleHealth.Api.Features.Admins.UpdateReceptionist;
using TeleHealth.Api.Features.Admins.UpdateSettings;
using TeleHealth.Api.Features.Appointments.Book;
using TeleHealth.Api.Features.Appointments.GetAllAppointments;
using TeleHealth.Api.Features.Appointments.GetAppointmentByIdForDoctor;
using TeleHealth.Api.Features.Appointments.GetAppointmentsById;
using TeleHealth.Api.Features.Appointments.GetAppointmentStatuses;
using TeleHealth.Api.Features.Appointments.Remind;
using TeleHealth.Api.Features.Appointments.SubmitConsultation;
using TeleHealth.Api.Features.Appointments.UpdateAppointmentByIdForReceptionist;
using TeleHealth.Api.Features.Doctors.CreateDoctor;
using TeleHealth.Api.Features.Doctors.DeleteDoctor;
using TeleHealth.Api.Features.Doctors.GetAllDoctors;
using TeleHealth.Api.Features.Doctors.GetDoctorPatientAppointments;
using TeleHealth.Api.Features.Doctors.GetDoctorPatients;
using TeleHealth.Api.Features.Doctors.GetSchedule;
using TeleHealth.Api.Features.Doctors.UpdateDoctor;
using TeleHealth.Api.Features.LabReports.Complete;
using TeleHealth.Api.Features.LabReports.Download;
using TeleHealth.Api.Features.LabReports.GetAllLabReports;
using TeleHealth.Api.Features.LabReports.GetAllPatients;
using TeleHealth.Api.Features.LabReports.InitializeUpload;
using TeleHealth.Api.Features.Patients.CancelAppointment;
using TeleHealth.Api.Features.Patients.DeletePatient;
using TeleHealth.Api.Features.Patients.GetAllAppointments;
using TeleHealth.Api.Features.Patients.GetAllPatientsForClinicStaff;
using TeleHealth.Api.Features.Patients.GetAllPatientsForReceptionist;
using TeleHealth.Api.Features.Patients.GetAppointmentByIdOrSlug;
using TeleHealth.Api.Features.Patients.GetPatientByIdForReceptionist;
using TeleHealth.Api.Features.Patients.GetPatientHistoryForReceptionist;
using TeleHealth.Api.Features.Patients.GetProfile;
using TeleHealth.Api.Features.Patients.RescheduleAppointment;
using TeleHealth.Api.Features.Patients.UpdateMedicalRecord;
using TeleHealth.Api.Features.Patients.UpdatePatientRecord;
using TeleHealth.Api.Features.Schedules.CreateSchedule;
using TeleHealth.Api.Features.Schedules.DeleteSchedule;
using TeleHealth.Api.Features.Schedules.GetAllAvailableSchedules;
using TeleHealth.Api.Features.Schedules.GetDailySchedulesForReceptionist;
using TeleHealth.Api.Features.SystemSettings.GetPublic;
using TeleHealth.Api.Features.Users.ChangePassword;
using TeleHealth.Api.Features.Users.Create;
using TeleHealth.Api.Features.Users.DoctorProfile;
using TeleHealth.Api.Features.Users.GetMe;
using TeleHealth.Api.Features.Users.Login;
using TeleHealth.Api.Features.Users.ProfileAvatar;
using TeleHealth.Api.Features.Users.ReceptionistProfile;
using TeleHealth.Api.Features.Users.Register;
using TeleHealth.Api.Features.Users.UpdateProfile;

namespace TeleHealth.Api.Common.Extensions;

public static class EndpointMappingExtensions
{
    public static RouteGroupBuilder MapAllEndpoints(this RouteGroupBuilder api)
    {
        api.MapLoginEndpoint();
        api.MapRegisterPatientEndpoint();
        api.MapCreateUserEndpoint();
        api.MapGetProfileEndpoint();
        api.MapUpdateMedicalRecordEndpoint();
        api.MapBookAppointmentEndpoint();
        api.MapGetMeEndpoint();
        api.MapGetDoctorProfileEndpoint();
        api.MapGetReceptionistProfileEndpoint();
        api.MapUpdateReceptionistProfileEndpoint();
        api.MapGetAvatarUploadUrlEndpoint();
        api.MapUpdateAvatarEndpoint();
        api.MapUpdateProfileEndpoint();
        api.MapChangePasswordEndpoint();
        api.MapGetAllAppointmentsEndpoint();
        api.MapGetAllAppointmentsForReceptionistEndpoint();
        api.MapGetAppointmentByIdForReceptionistEndpoint();
        api.MapGetAppointmentStatusesEndpoint();
        api.MapUpdateAppointmentByReceptionistEndpoint();
        api.MapRemindPatientEndpoint();
        api.MapGetAppointmentByIdForDoctorEndpoint();
        api.MapSubmitConsultationEndpoint();
        api.MapGetAppointmentByIdOrSlugEndpoint();
        api.MapRescheduleAppointmentEndpoint();
        api.MapCancelAppointmentEndpoint();
        api.MapAdminGetAllDepartmentsEndpoint();
        api.MapAdminCreateDepartmentEndpoint();
        api.MapAdminUpdateDepartmentEndpoint();
        api.MapAdminDeleteDepartmentEndpoint();
        api.MapAdminGetAllReceptionistsEndpoint();
        api.MapAdminCreateReceptionistEndpoint();
        api.MapAdminUpdateReceptionistEndpoint();
        api.MapAdminDeleteReceptionistEndpoint();
        api.MapAdminGetAllLabTechsEndpoint();
        api.MapAdminGetLabTechEndpoint();
        api.MapAdminCreateLabTechEndpoint();
        api.MapAdminUpdateLabTechEndpoint();
        api.MapAdminDeleteLabTechEndpoint();
        api.MapAdminGetAuditLogsEndpoint();
        api.MapAdminGetDashboardSummaryEndpoint();
        api.MapAdminGetSettingsEndpoint();
        api.MapAdminUpdateSettingsEndpoint();
        api.MapCreateDoctorEndpoint();
        api.MapGetAllDoctorsEndpoint();
        api.MapUpdateDoctorEndpoint();
        api.MapDeleteDoctorEndpoint();
        api.MapCreateScheduleEndpoint();
        api.MapDeleteScheduleEndpoint();
        api.MapGetAllAvailableSchedulesEndpoint();
        api.MapGetDailySchedulesEndpoint();
        api.MapGetDoctorScheduleEndpoint();
        api.MapInitializeLabReportEndpoint();
        api.MapCompleteLabReportsEndpoint();
        api.MapDownloadLabReportEndpoint();
        api.MapGetAllLabReportsEndpoint();
        api.MapLabTechGetAllPatientsEndpoint();
        api.MapReceptionistGetAllPatientsEndpoint();
        api.MapReceptionistGetPatientByIdEndpoint();
        api.MapReceptionistGetPatientHistoryEndpoint();
        api.MapClinicStaffGetAllPatientsEndpoint();
        api.MapUpdatePatientRecordEndpoint();
        api.MapDeletePatientEndpoint();
        api.MapGetDoctorPatientsEndpoint();
        api.MapGetDoctorPatientAppointmentsEndpoint();
        api.MapGetPublicSystemSettingsEndpoint();

        return api;
    }
}
