import { useForm } from "@tanstack/react-form";
import { useNavigate } from "@tanstack/react-router";
import { zodValidator } from "@tanstack/zod-form-adapter";
import { z } from "zod";
// Shadcn UI Components (Assuming you generated these via the shadcn CLI)
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
// State & API (Generated by Orval)
import { useLoginUser } from "../../api/generated/authentication";
import { useAuthStore } from "../../store/useAuthStore";

// 1. Zod Schema
const loginSchema = z.object({
  email: z.string().email("Invalid email address"),
  password: z.string().min(8, "Password must be at least 8 characters"),
});

export function LoginForm() {
  const navigate = useNavigate();
  const setAuth = useAuthStore((state) => state.setAuth);

  // 2. Orval TanStack Query Mutation
  const loginMutation = useLoginUser();

  // 3. TanStack Form Setup
  const form = useForm({
    defaultValues: {
      email: "",
      password: "",
    },
    validatorAdapter: zodValidator(),
    onSubmit: async ({ value }) => {
      // Trigger the backend API call
      loginMutation.mutate(
        { data: value },
        {
          onSuccess: () => {
            // HttpOnly cookie is set! Update global Zustand state
            setAuth({
              publicId: "123",
              email: value.email,
              firstName: "User",
              role: "Patient",
            });

            // Redirect to the protected dashboard via TanStack Router
            navigate({ to: "/dashboard" });
          },
          onError: (error: any) => {
            // The ASP.NET ProblemDetails JSON is caught here
            console.error(
              "Login failed:",
              error.data?.title || "Unknown error"
            );
          },
        }
      );
    },
  });

  return (
    <div className="flex min-h-[80vh] items-center justify-center">
      <Card className="w-full max-w-md shadow-lg">
        <CardHeader>
          <CardTitle className="text-center font-bold text-2xl">
            TeleHealth Login
          </CardTitle>
        </CardHeader>
        <CardContent>
          {/* Form wrapper */}
          <form
            className="space-y-6"
            onSubmit={(e) => {
              e.preventDefault();
              e.stopPropagation();
              form.handleSubmit();
            }}
          >
            {/* Email Field */}
            <form.Field
              children={(field) => (
                <div className="space-y-2">
                  <Label htmlFor={field.name}>Email</Label>
                  <Input
                    className={
                      field.state.meta.errors.length ? "border-destructive" : ""
                    }
                    id={field.name}
                    name={field.name}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                    placeholder="doctor@telehealth.com"
                    type="email"
                    value={field.state.value}
                  />
                  {/* Validation Error Message */}
                  {field.state.meta.errors.length > 0 && (
                    <p className="text-destructive text-sm">
                      {field.state.meta.errors.join(", ")}
                    </p>
                  )}
                </div>
              )}
              name="email"
              validators={{ onChange: loginSchema.shape.email }}
            />

            {/* Password Field */}
            <form.Field
              children={(field) => (
                <div className="space-y-2">
                  <Label htmlFor={field.name}>Password</Label>
                  <Input
                    className={
                      field.state.meta.errors.length ? "border-destructive" : ""
                    }
                    id={field.name}
                    name={field.name}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                    placeholder="••••••••"
                    type="password"
                    value={field.state.value}
                  />
                  {field.state.meta.errors.length > 0 && (
                    <p className="text-destructive text-sm">
                      {field.state.meta.errors.join(", ")}
                    </p>
                  )}
                </div>
              )}
              name="password"
              validators={{ onChange: loginSchema.shape.password }}
            />

            {/* Global API Error Alert (Optional) */}
            {loginMutation.isError && (
              <div className="rounded-md bg-destructive/10 p-3 text-destructive-foreground text-sm">
                Invalid email or password. Please try again.
              </div>
            )}

            {/* Submit Button (Subscribed to form state for performance!) */}
            <form.Subscribe
              children={([canSubmit, isSubmitting]) => (
                <Button
                  className="w-full"
                  disabled={
                    !canSubmit || isSubmitting || loginMutation.isPending
                  }
                  type="submit"
                >
                  {loginMutation.isPending ? "Authenticating..." : "Login"}
                </Button>
              )}
              selector={(state) => [state.canSubmit, state.isSubmitting]}
            />
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
