// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeleHealth.Api.Infrastructure.Persistence;

#nullable disable

namespace TeleHealth.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260428173708_AddSystemSettings")]
    partial class AddSystemSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("receive_count");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_inbox_state");

                    b.HasAlternateKey("MessageId", "ConsumerId")
                        .HasName("ak_inbox_state_message_id_consumer_id");

                    b.HasIndex("Delivered")
                        .HasDatabaseName("ix_inbox_state_delivered");

                    b.ToTable("inbox_state", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destination_address");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueue_time");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fault_address");

                    b.Property<string>("Headers")
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_consumer_id");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("response_address");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_time");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_address");

                    b.HasKey("SequenceNumber")
                        .HasName("pk_outbox_message");

                    b.HasIndex("EnqueueTime")
                        .HasDatabaseName("ix_outbox_message_enqueue_time");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("ix_outbox_message_expiration_time");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_outbox_id_sequence_number");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("OutboxId")
                        .HasName("pk_outbox_state");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_outbox_state_created");

                    b.ToTable("outbox_state", (string)null);
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<Instant?>("CheckInDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_date_time");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<long>("ScheduleId")
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VisitReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("visit_reason");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Symptoms", "TeleHealth.Api.Domain.Entities.Appointment.Symptoms#Symptom", b1 =>
                        {
                            b1.Property<string>("Duration")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Severity")
                                .IsRequired();

                            b1
                                .ToJson("symptoms")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_appointments_created_by_user_id");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_appointments_doctor_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_appointments_patient_id");

                    b.HasIndex("ScheduleId")
                        .IsUnique()
                        .HasDatabaseName("uq_appointments_schedule_active")
                        .HasFilter("deleted_at is null");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_appointments_slug");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_appointments_status_id");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.AppointmentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_code");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsTerminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_appointment_statuses");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_appointment_statuses_slug");

                    b.ToTable("appointment_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#3B82F6",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Appointment confirmed and scheduled",
                            IsTerminal = false,
                            Name = "Booked",
                            Slug = "booked"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#10B981",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Patient has arrived at clinic",
                            IsTerminal = false,
                            Name = "Checked In",
                            Slug = "checked-in"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#F59E0B",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Consultation is currently ongoing",
                            IsTerminal = false,
                            Name = "In Progress",
                            Slug = "in-progress"
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#059669",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Appointment finished successfully",
                            IsTerminal = true,
                            Name = "Completed",
                            Slug = "completed"
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "#EF4444",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Appointment was cancelled",
                            IsTerminal = true,
                            Name = "Cancelled",
                            Slug = "cancelled"
                        },
                        new
                        {
                            Id = 6,
                            ColorCode = "#6B7280",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Patient did not attend the appointment",
                            IsTerminal = true,
                            Name = "No Show",
                            Slug = "no-show"
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.PrimitiveCollection<string[]>("ChangedColumns")
                        .HasColumnType("text[]")
                        .HasColumnName("changed_columns");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<JsonDocument>("NewValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<JsonDocument>("OldValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<bool>("PerformedBySystem")
                        .HasColumnType("boolean")
                        .HasColumnName("performed_by_system");

                    b.Property<long?>("PerformedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("performed_by_user_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<long>("RecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("table_name");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("PerformedByUserId")
                        .HasDatabaseName("ix_audit_logs_performed_by_user_id");

                    b.ToTable("audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("chk_audit_action", "action in ('INSERT', 'UPDATE', 'DELETE')");

                            t.HasCheckConstraint("chk_audit_logs_actor", "performed_by_system or performed_by_user_id is not null");
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Consultation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("appointment_id");

                    b.Property<Instant>("ConsultationDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consultation_date_time");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<LocalDate?>("FollowUpDate")
                        .HasColumnType("date")
                        .HasColumnName("follow_up_date");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ConsultationNotes", "TeleHealth.Api.Domain.Entities.Consultation.ConsultationNotes#ConsultationNote", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Assessment")
                                .IsRequired();

                            b1.Property<string>("Objective")
                                .IsRequired();

                            b1.Property<string>("Plan")
                                .IsRequired();

                            b1.Property<string>("Subjective")
                                .IsRequired();

                            b1
                                .ToJson("consultation_notes")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_consultations");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("uq_consultations_appointment_active")
                        .HasFilter("deleted_at is null");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_consultations_slug");

                    b.ToTable("consultations", (string)null);
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_slug");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Primary care and general health services",
                            Name = "General Practice",
                            Slug = "general"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Heart and cardiovascular health",
                            Name = "Cardiology",
                            Slug = "cardiology"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Children and adolescent healthcare",
                            Name = "Pediatrics",
                            Slug = "pediatrics"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Bone, joint, and muscle conditions",
                            Name = "Orthopedics",
                            Slug = "orthopedics"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Skin conditions and treatments",
                            Name = "Dermatology",
                            Slug = "dermatology"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Brain and nervous system disorders",
                            Name = "Neurology",
                            Slug = "neurology"
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<decimal?>("ConsultationFee")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("consultation_fee");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("license_number");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("specialization");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Qualifications", "TeleHealth.Api.Domain.Entities.Doctor.Qualifications#Qualification", b1 =>
                        {
                            b1.Property<string>("Degree")
                                .IsRequired();

                            b1.Property<string>("Institution")
                                .IsRequired();

                            b1.Property<int>("Year");

                            b1
                                .ToJson("qualifications")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_doctors");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_doctors_department_id");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_doctors_license_active")
                        .HasFilter("deleted_at is null");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_doctors_slug");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_doctors_user_active")
                        .HasFilter("deleted_at is null");

                    b.ToTable("doctors", null, t =>
                        {
                            t.HasCheckConstraint("chk_doctors_fee_nonnegative", "consultation_fee is null or consultation_fee >= 0");
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.DoctorSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<LocalDate>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<LocalTime>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<LocalTime>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_doctor_schedules");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_doctor_schedules_doctor_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_doctor_schedules_status_id");

                    b.ToTable("doctor_schedules", null, t =>
                        {
                            t.HasCheckConstraint("chk_schedules_time_range", "end_time > start_time");
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.LabReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ConsultationId")
                        .HasColumnType("bigint")
                        .HasColumnName("consultation_id");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("report_type");

                    b.Property<string>("S3ObjectKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("s3object_key");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Instant?>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Biomarkers", "TeleHealth.Api.Domain.Entities.LabReport.Biomarkers#Biomarker", b1 =>
                        {
                            b1.Property<string>("Flag")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("ReferenceRange")
                                .IsRequired();

                            b1.Property<string>("Unit")
                                .IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1
                                .ToJson("biomarkers")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_lab_reports");

                    b.HasIndex("ConsultationId")
                        .HasDatabaseName("ix_lab_reports_consultation_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_lab_reports_patient_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_lab_reports_slug");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_lab_reports_status_id");

                    b.ToTable("lab_reports", (string)null);
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.LabReportStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_code");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_lab_report_statuses");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_lab_report_statuses_slug");

                    b.ToTable("lab_report_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#6B7280",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Waiting for lab technician to upload PDF",
                            Name = "Pending Upload",
                            Slug = "pending"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#F59E0B",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Lambda function is extracting biomarkers",
                            Name = "Processing",
                            Slug = "processing"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#10B981",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Lab report successfully processed and ready",
                            Name = "Completed",
                            Slug = "completed"
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#EF4444",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Failed to process or invalid lab report file",
                            Name = "Rejected",
                            Slug = "rejected"
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<long>("RecipientUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipient_user_id");

                    b.Property<long?>("RelatedEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("related_entity_type");

                    b.Property<Instant?>("SendAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("send_at");

                    b.Property<string>("SnsMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sns_message_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("RecipientUserId")
                        .HasDatabaseName("ix_notifications_recipient_user_id");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("chk_notification_status", "status in ('queued', 'sent', 'failed')");
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("blood_group");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Allergies", "TeleHealth.Api.Domain.Entities.Patient.Allergies#Allergy", b1 =>
                        {
                            b1.Property<string>("Allergen")
                                .IsRequired();

                            b1.Property<string>("Reaction")
                                .IsRequired();

                            b1.Property<string>("Severity")
                                .IsRequired();

                            b1
                                .ToJson("allergies")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EmergencyContact", "TeleHealth.Api.Domain.Entities.Patient.EmergencyContact#EmergencyContact", b1 =>
                        {
                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(16);

                            b1.Property<string>("Relationship")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1
                                .ToJson("emergency_contact")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_slug");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_patients_user_active")
                        .HasFilter("deleted_at is null");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Prescription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConsultationId")
                        .HasColumnType("bigint")
                        .HasColumnName("consultation_id");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dosage");

                    b.Property<short>("DurationDays")
                        .HasColumnType("smallint")
                        .HasColumnName("duration_days");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("frequency");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("medication_name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Instructions", "TeleHealth.Api.Domain.Entities.Prescription.Instructions#Instruction", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("MissedDose")
                                .IsRequired();

                            b1.Property<string>("Storage")
                                .IsRequired();

                            b1.Property<string>("TakeWith")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Warnings")
                                .IsRequired();

                            b1
                                .ToJson("instructions")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_prescriptions");

                    b.HasIndex("ConsultationId")
                        .HasDatabaseName("ix_prescriptions_consultation_id");

                    b.ToTable("prescriptions", null, t =>
                        {
                            t.HasCheckConstraint("chk_prescriptions_duration_positive", "duration_days > 0");
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_slug");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "System administrator with full access",
                            Name = "Administrator",
                            Slug = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Medical practitioner who can manage appointments and consultations",
                            Name = "Doctor",
                            Slug = "doctor"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Patient user who can book appointments and view medical records",
                            Name = "Patient",
                            Slug = "patient"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Front desk staff who manages appointments",
                            Name = "Receptionist",
                            Slug = "receptionist"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Laboratory staff who process and upload lab reports",
                            Name = "Lab Technician",
                            Slug = "lab-tech"
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.ScheduleStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_code");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_schedule_statuses");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_schedule_statuses_slug");

                    b.ToTable("schedule_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#10B981",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Slot is open for booking",
                            Name = "Available",
                            Slug = "available"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#3B82F6",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Slot has been reserved by a patient",
                            Name = "Booked",
                            Slug = "booked"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#EF4444",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Slot is blocked by doctor or admin",
                            Name = "Blocked",
                            Slug = "blocked"
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.SystemOperatingHour", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<LocalTime?>("CloseTime")
                        .HasColumnType("time")
                        .HasColumnName("close_time");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_open");

                    b.Property<LocalTime?>("OpenTime")
                        .HasColumnType("time")
                        .HasColumnName("open_time");

                    b.Property<long>("SystemSettingId")
                        .HasColumnType("bigint")
                        .HasColumnName("system_settings_id");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_system_operating_hours");

                    b.HasIndex("SystemSettingId")
                        .HasDatabaseName("ix_system_operating_hours_system_setting_id");

                    b.ToTable("system_operating_hours", (string)null);
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clinic_name");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("DefaultAppointmentDurationMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("default_appointment_duration_minutes");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<string>("SupportEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("support_email");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_system_settings");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_system_settings_slug");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<LocalDate>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<char>("Gender")
                        .HasColumnType("character(1)")
                        .HasColumnName("gender");

                    b.Property<string>("IcNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("ic_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "TeleHealth.Api.Domain.Entities.User.Address#Address", b1 =>
                        {
                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasJsonPropertyName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasJsonPropertyName("country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasJsonPropertyName("postal_code");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasJsonPropertyName("state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasJsonPropertyName("street");

                            b1
                                .ToJson("address")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email_active")
                        .HasFilter("deleted_at is null");

                    b.HasIndex("IcNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_users_ic_active")
                        .HasFilter("deleted_at is null");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_users_slug_active")
                        .HasFilter("deleted_at is null");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_users_username_active")
                        .HasFilter("deleted_at is null");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("chk_users_dob_not_future", "date_of_birth <= current_date");

                            t.HasCheckConstraint("chk_users_gender", "gender in ('M', 'F', 'O', 'N')");
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("RoleId", "UserId")
                        .HasName("pk_user_roles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .HasConstraintName("fk_outbox_message_outbox_state_outbox_id");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId")
                        .HasConstraintName("fk_outbox_message_inbox_state_inbox_message_id_inbox_consumer_");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("TeleHealth.Api.Domain.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_users_created_by_user_id");

                    b.HasOne("TeleHealth.Api.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_doctors_doctor_id");

                    b.HasOne("TeleHealth.Api.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_patients_patient_id");

                    b.HasOne("TeleHealth.Api.Domain.Entities.DoctorSchedule", "DoctorSchedule")
                        .WithOne("Appointment")
                        .HasForeignKey("TeleHealth.Api.Domain.Entities.Appointment", "ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_doctor_schedules_schedule_id");

                    b.HasOne("TeleHealth.Api.Domain.Entities.AppointmentStatus", "AppointmentStatus")
                        .WithMany("Appointments")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_appointment_statuses_status_id");

                    b.Navigation("AppointmentStatus");

                    b.Navigation("Doctor");

                    b.Navigation("DoctorSchedule");

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("TeleHealth.Api.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedByUserId")
                        .HasConstraintName("fk_audit_logs_users_performed_by_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Consultation", b =>
                {
                    b.HasOne("TeleHealth.Api.Domain.Entities.Appointment", "Appointment")
                        .WithOne("Consultation")
                        .HasForeignKey("TeleHealth.Api.Domain.Entities.Consultation", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consultations_appointments_appointment_id");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("TeleHealth.Api.Domain.Entities.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doctors_departments_department_id");

                    b.HasOne("TeleHealth.Api.Domain.Entities.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("TeleHealth.Api.Domain.Entities.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doctors_users_user_id");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.DoctorSchedule", b =>
                {
                    b.HasOne("TeleHealth.Api.Domain.Entities.Doctor", "Doctor")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doctor_schedules_doctors_doctor_id");

                    b.HasOne("TeleHealth.Api.Domain.Entities.ScheduleStatus", "ScheduleStatus")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doctor_schedules_schedule_statuses_status_id");

                    b.Navigation("Doctor");

                    b.Navigation("ScheduleStatus");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.LabReport", b =>
                {
                    b.HasOne("TeleHealth.Api.Domain.Entities.Consultation", "Consultation")
                        .WithMany("LabReports")
                        .HasForeignKey("ConsultationId")
                        .HasConstraintName("fk_lab_reports_consultations_consultation_id");

                    b.HasOne("TeleHealth.Api.Domain.Entities.Patient", "Patient")
                        .WithMany("LabReports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lab_reports_patients_patient_id");

                    b.HasOne("TeleHealth.Api.Domain.Entities.LabReportStatus", "LabReportStatus")
                        .WithMany("LabReports")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lab_reports_lab_report_statuses_status_id");

                    b.Navigation("Consultation");

                    b.Navigation("LabReportStatus");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Notification", b =>
                {
                    b.HasOne("TeleHealth.Api.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientUserId")
                        .HasConstraintName("fk_notifications_users_recipient_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Patient", b =>
                {
                    b.HasOne("TeleHealth.Api.Domain.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("TeleHealth.Api.Domain.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patients_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("TeleHealth.Api.Domain.Entities.Consultation", "Consultation")
                        .WithMany("Prescriptions")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prescriptions_consultations_consultation_id");

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.SystemOperatingHour", b =>
                {
                    b.HasOne("TeleHealth.Api.Domain.Entities.SystemSetting", "SystemSetting")
                        .WithMany("OperatingHours")
                        .HasForeignKey("SystemSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_system_operating_hours_system_settings");

                    b.Navigation("SystemSetting");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("TeleHealth.Api.Domain.Entities.Role", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("TeleHealth.Api.Domain.Entities.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Consultation")
                        .IsRequired();
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.AppointmentStatus", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Consultation", b =>
                {
                    b.Navigation("LabReports");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorSchedules");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.DoctorSchedule", b =>
                {
                    b.Navigation("Appointment")
                        .IsRequired();
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.LabReportStatus", b =>
                {
                    b.Navigation("LabReports");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("LabReports");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.ScheduleStatus", b =>
                {
                    b.Navigation("DoctorSchedules");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.SystemSetting", b =>
                {
                    b.Navigation("OperatingHours");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("AuditLogs");

                    b.Navigation("Doctor");

                    b.Navigation("Notifications");

                    b.Navigation("Patient");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
