// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeleHealth.Api.Infrastructure.Persistence;

#nullable disable

namespace TeleHealth.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260323102730_LookupAndIdentityProfileTable")]
    partial class LookupAndIdentityProfileTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.AppointmentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_code");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsTerminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_appointment_statuses");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_appointment_statuses_slug");

                    b.ToTable("appointment_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#3B82F6",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Appointment confirmed and scheduled",
                            IsTerminal = false,
                            Name = "Booked",
                            Slug = "booked"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#10B981",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Patient has arrived at clinic",
                            IsTerminal = false,
                            Name = "Checked In",
                            Slug = "checked-in"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#F59E0B",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Consultation is currently ongoing",
                            IsTerminal = false,
                            Name = "In Progress",
                            Slug = "in-progress"
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#059669",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Appointment finished successfully",
                            IsTerminal = true,
                            Name = "Completed",
                            Slug = "completed"
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "#EF4444",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Appointment was cancelled",
                            IsTerminal = true,
                            Name = "Cancelled",
                            Slug = "cancelled"
                        },
                        new
                        {
                            Id = 6,
                            ColorCode = "#6B7280",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Patient did not attend the appointment",
                            IsTerminal = true,
                            Name = "No Show",
                            Slug = "no-show"
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_slug");

                    b.ToTable("departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Primary care and general health services",
                            Name = "General Practice",
                            Slug = "general"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Heart and cardiovascular health",
                            Name = "Cardiology",
                            Slug = "cardiology"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Children and adolescent healthcare",
                            Name = "Pediatrics",
                            Slug = "pediatrics"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Bone, joint, and muscle conditions",
                            Name = "Orthopedics",
                            Slug = "orthopedics"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Skin conditions and treatments",
                            Name = "Dermatology",
                            Slug = "dermatology"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Brain and nervous system disorders",
                            Name = "Neurology",
                            Slug = "neurology"
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<decimal?>("ConsultationFee")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("consultation_fee");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("license_number");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("specialization");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Qualifications", "TeleHealth.Api.Domain.Entities.Doctor.Qualifications#Qualification", b1 =>
                        {
                            b1.Property<string>("Degree")
                                .IsRequired();

                            b1.Property<string>("Institution")
                                .IsRequired();

                            b1.Property<int>("Year");

                            b1
                                .ToJson("qualifications")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_doctors");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_doctors_department_id");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_doctors_license_active")
                        .HasFilter("deleted_at is null");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_doctors_slug");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_doctors_user_active")
                        .HasFilter("deleted_at is null");

                    b.ToTable("doctors", null, t =>
                        {
                            t.HasCheckConstraint("chk_doctors_fee_nonnegative", "consultation_fee is null or consultation_fee >= 0");
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.LabReportStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_code");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_lab_report_statuses");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_lab_report_statuses_slug");

                    b.ToTable("lab_report_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#6B7280",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Waiting for lab technician to upload PDF",
                            Name = "Pending Upload",
                            Slug = "pending"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#F59E0B",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Lambda function is extracting biomarkers",
                            Name = "Processing",
                            Slug = "processing"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#10B981",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Lab report successfully processed and ready",
                            Name = "Completed",
                            Slug = "completed"
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#EF4444",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Failed to process or invalid lab report file",
                            Name = "Rejected",
                            Slug = "rejected"
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("blood_group");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Allergies", "TeleHealth.Api.Domain.Entities.Patient.Allergies#Allergies", b1 =>
                        {
                            b1.Property<string>("Allergen")
                                .IsRequired();

                            b1.Property<string>("Reaction")
                                .IsRequired();

                            b1.Property<string>("Severity")
                                .IsRequired();

                            b1
                                .ToJson("allergies")
                                .HasColumnType("jsonb");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EmergencyContact", "TeleHealth.Api.Domain.Entities.Patient.EmergencyContact#EmergencyContact", b1 =>
                        {
                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(16);

                            b1.Property<string>("Relationship")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1
                                .ToJson("emergency_contact")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_slug");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_patients_user_active")
                        .HasFilter("deleted_at is null");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_slug");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "System administrator with full access",
                            Name = "Administrator",
                            Slug = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Medical practitioner who can manage appointments and consultations",
                            Name = "Doctor",
                            Slug = "doctor"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Patient user who can book appointments and view medical records",
                            Name = "Patient",
                            Slug = "patient"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Front desk staff who manages appointments",
                            Name = "Receptionist",
                            Slug = "receptionist"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Laboratory staff who process and upload lab reports",
                            Name = "Lab Technician",
                            Slug = "lab-tech"
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.ScheduleStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_code");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_schedule_statuses");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_schedule_statuses_slug");

                    b.ToTable("schedule_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#10B981",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Slot is open for booking",
                            Name = "Available",
                            Slug = "available"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#3B82F6",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Slot has been reserved by a patient",
                            Name = "Booked",
                            Slug = "booked"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#EF4444",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(0L),
                            Description = "Slot is blocked by doctor or admin",
                            Name = "Blocked",
                            Slug = "blocked"
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<LocalDate>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<char>("Gender")
                        .HasColumnType("character(1)")
                        .HasColumnName("gender");

                    b.Property<string>("IcNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("ic_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "TeleHealth.Api.Domain.Entities.User.Address#Address", b1 =>
                        {
                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1
                                .ToJson("address")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email_active")
                        .HasFilter("deleted_at is null");

                    b.HasIndex("IcNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_users_ic_active")
                        .HasFilter("deleted_at is null");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("uq_users_slug_active")
                        .HasFilter("deleted_at is null");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_users_username_active")
                        .HasFilter("deleted_at is null");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("chk_users_dob_not_future", "date_of_birth <= current_date");

                            t.HasCheckConstraint("chk_users_gender", "gender in ('M', 'F', 'O', 'N')");
                        });
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("RoleId", "UserId")
                        .HasName("pk_user_roles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("TeleHealth.Api.Domain.Entities.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doctors_departments_department_id");

                    b.HasOne("TeleHealth.Api.Domain.Entities.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("TeleHealth.Api.Domain.Entities.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doctors_users_user_id");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Patient", b =>
                {
                    b.HasOne("TeleHealth.Api.Domain.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("TeleHealth.Api.Domain.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patients_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("TeleHealth.Api.Domain.Entities.Role", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("TeleHealth.Api.Domain.Entities.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Department", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TeleHealth.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
