using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TeleHealth.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddSystemSettings : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                create table if not exists system_settings (
                    id bigint generated by default as identity,
                    slug character varying(50) not null,
                    clinic_name character varying(100) not null,
                    support_email character varying(255) not null,
                    default_appointment_duration_minutes smallint not null,
                    created_at timestamp with time zone not null default now(),
                    updated_at timestamp with time zone,
                    constraint pk_system_settings primary key (id)
                );

                create unique index if not exists ix_system_settings_slug
                    on system_settings (slug);

                create table if not exists system_operating_hours (
                    id bigint generated by default as identity,
                    system_settings_id bigint not null,
                    day_of_week smallint not null,
                    is_open boolean not null default true,
                    open_time time,
                    close_time time,
                    created_at timestamp with time zone not null default now(),
                    updated_at timestamp with time zone,
                    constraint pk_system_operating_hours primary key (id),
                    constraint fk_system_operating_hours_system_settings
                        foreign key (system_settings_id)
                        references system_settings (id)
                        on delete cascade
                );

                create index if not exists ix_system_operating_hours_system_setting_id
                    on system_operating_hours (system_settings_id);

                insert into system_settings (slug, clinic_name, support_email, default_appointment_duration_minutes)
                select 'clinic-settings', 'TeleHealth Medical Centre', 'support@telehealth.com', 30
                where not exists (
                    select 1 from system_settings where slug = 'clinic-settings'
                );

                insert into system_operating_hours (system_settings_id, day_of_week, is_open, open_time, close_time)
                select settings.id, hours.day_of_week, hours.is_open, hours.open_time, hours.close_time
                from system_settings settings
                cross join (
                    values
                        (1::smallint, true, time '09:00', time '17:00'),
                        (2::smallint, true, time '09:00', time '17:00'),
                        (3::smallint, true, time '09:00', time '17:00'),
                        (4::smallint, true, time '09:00', time '17:00'),
                        (5::smallint, true, time '09:00', time '17:00'),
                        (6::smallint, true, time '09:00', time '13:00'),
                        (7::smallint, false, null::time, null::time)
                ) as hours(day_of_week, is_open, open_time, close_time)
                where settings.slug = 'clinic-settings'
                    and not exists (
                        select 1
                        from system_operating_hours existing
                        where existing.system_settings_id = settings.id
                            and existing.day_of_week = hours.day_of_week
                    );
                """
            );
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "system_operating_hours");

            migrationBuilder.DropTable(name: "system_settings");
        }
    }
}
