services:

  api:
    container_name: telehealth_api
    build:
      context: "../"
      target: final
      dockerfile: "backend/src/TeleHealth.Api/Dockerfile"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_HTTP_PORTS: ${ASPNETCORE_HTTP_PORT}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL}
    ports:
      - "${ASPNETCORE_HTTP_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
      seq:
        condition: service_started
      localstack:
        condition: service_started
    restart: unless-stopped

  db:
    container_name: telehealth_db
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  localstack:
    container_name: "telehealth_awslocal"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # External services port range
    environment:
      DEBUG: ${DEBUG:-0}
      SERVICES: "s3,sqs,sns"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - localstack-data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

  seq:
    image: datalust/seq:2025
    container_name: telehealth_seq
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_ADMIN_PASSWORD}
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq-data:/data
    restart: unless-stopped

volumes:
  db-data:
  localstack-data:
  seq-data: