/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LocalDate } from "./LocalDate";

export interface CreateUserCommand {
  dateOfBirth: LocalDate;
  email: string;
  firstName: string;
  gender: string;
  icNumber: string;
  lastName: string;
  password: string;
  phone: string;
  username: string;
}
