/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */

// biome-ignore lint/complexity/noBannedTypes: generated file
export type LocalTime = {};
