/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Allergy } from "./Allergy";
import type { EmergencyContact } from "./EmergencyContact";

export interface PatientProfileDto {
  /** @nullable */
  allergies: Allergy[] | null;
  /** @nullable */
  bloodGroup: string | null;
  email: string;
  emergencyContact: null | EmergencyContact;
  firstName: string;
  lastName: string;
  patientPublicId: string;
  role: string;
  userPublicId: string;
}
