/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Allergy } from './Allergy';
import type { LocalDate } from './LocalDate';
import type { LocalTime } from './LocalTime';
import type { Symptom } from './Symptom';

export interface ReceptionistAppointmentDetailDto {
  publicId?: string;
  slug?: string;
  visitReason?: string;
  /** @nullable */
  cancellationReason?: string | null;
  patientName?: string;
  /** @nullable */
  bloodGroup?: string | null;
  /** @nullable */
  allergies?: Allergy[] | null;
  doctorName?: string;
  specialization?: string;
  date?: LocalDate;
  startTime?: LocalTime;
  endTime?: LocalTime;
  status?: string;
  statusColorCode?: string;
  /** @nullable */
  symptoms?: Symptom[] | null;
}
