/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LocalDate } from "./LocalDate";

export interface RegisterPatientCommand {
  dateOfBirth: LocalDate;
  email: string;
  firstName: string;
  /**
   * @minLength 1
   * @maxLength 1
   */
  gender: string;
  icNumber: string;
  lastName: string;
  password: string;
  username: string;
}
