/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Allergy } from "./Allergy";
import type { EmergencyContact } from "./EmergencyContact";

export interface UpdateMedicalRecordCommand {
  allergies: Allergy[];
  bloodGroup: string;
  emergencyContact: null | EmergencyContact;
}
