/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface AdminDepartmentDto {
  slug: string;
  name: string;
  /** @nullable */
  description?: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  staffMembers?: number | string;
}
