/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Instant } from "./Instant";

export interface AdminLabTechDto {
  publicId?: string;
  firstName: string;
  lastName: string;
  username: string;
  email: string;
  /** @nullable */
  phoneNumber?: string | null;
  slug: string;
  /** @nullable */
  avatarUrl?: string | null;
  createdAt?: Instant;
  deletedAt?: null | Instant;
}
