/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Address } from "./Address";
import type { LocalDate } from "./LocalDate";

export interface AdminCreateLabTechCommand {
  firstName: string;
  lastName: string;
  username: string;
  email: string;
  password: string;
  /** @nullable */
  phoneNumber: string | null;
  /**
   * @minLength 1
   * @maxLength 1
   */
  gender: string;
  dateOfBirth: LocalDate;
  icNumber: string;
  address: null | Address;
}
