/**
 * Generated by orval v8.7.0
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LocalTime } from "./LocalTime";

export interface AdminUpdateOperatingHourCommand {
  dayOfWeek: number;
  isOpen: boolean;
  openTime?: null | LocalTime;
  closeTime?: null | LocalTime;
}
