/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUpdateOperatingHourCommand } from './AdminUpdateOperatingHourCommand';

export interface AdminUpdateSettingsCommand {
  clinicName: string;
  supportEmail: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  defaultAppointmentDurationMinutes: number | string;
  operatingHours: AdminUpdateOperatingHourCommand[];
}
