/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LocalTime } from "./LocalTime";

export interface AdminOperatingHourDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  dayOfWeek: number | string;
  isOpen: boolean;
  openTime: null | LocalTime;
  closeTime: null | LocalTime;
}
