/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Address } from "./Address";
import type { LocalDate } from "./LocalDate";

export interface AdminUpdateReceptionistCommand {
  firstName: string;
  lastName: string;
  username: string;
  email: string;
  /** @nullable */
  phoneNumber?: string | null;
  gender: string;
  dateOfBirth: LocalDate;
  /** @nullable */
  address?: Address | null;
}
