/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface AdminDashboardSummaryDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  todayAppointments: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  patients: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  doctors: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  staff: number | string;
}
