/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Symptom } from './Symptom';

export interface BookAppointmentCommand {
  schedulePublicId: string;
  visitReason: string;
  /** @nullable */
  symptoms: Symptom[] | null;
}
