/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AllergyDto } from "./AllergyDto";
import type { EmergencyContactDto } from "./EmergencyContactDto";
import type { Instant } from "./Instant";
import type { LocalDate } from "./LocalDate";

export interface ClinicStaffPatientDto {
  patientPublicId: string;
  slug: string;
  firstName: string;
  lastName: string;
  fullName: string;
  dateOfBirth: LocalDate;
  phoneNumber: string;
  bloodGroup: string;
  /**
     * @minLength 1
     * @maxLength 1
     */
  gender: string;
  /** @nullable */
  allergies: AllergyDto[] | null;
  emergencyContact: null | EmergencyContactDto;
  joinedAt: Instant;
}
