/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LocalDate } from './LocalDate';
import type { PrescriptionDetailDto } from './PrescriptionDetailDto';

export interface ConsultationDetailDto {
  publicId?: string;
  subjective?: string;
  objective?: string;
  assessment?: string;
  plan?: string;
  followUpDate?: null | LocalDate;
  prescriptions?: PrescriptionDetailDto[];
}
