/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateDoctorQualificationCommand {
  degree: string;
  institution: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  year: number | string;
}
