/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateDoctorAddressCommand } from "./CreateDoctorAddressCommand";
import type { CreateDoctorQualificationCommand } from "./CreateDoctorQualificationCommand";
import type { LocalDate } from "./LocalDate";

export interface CreateDoctorCommand {
  firstName: string;
  lastName: string;
  username: string;
  email: string;
  password: string;
  /** @nullable */
  phoneNumber: string | null;
  gender: string;
  dateOfBirth: LocalDate;
  icNumber: string;
  /** @nullable */
  bio: string | null;
  specialization: string;
  licenseNumber: string;
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
   */
  consultationFee: number | string | null;
  departmentName: string;
  address: null | CreateDoctorAddressCommand;
  qualifications: CreateDoctorQualificationCommand[];
}
