/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface DoctorListDto {
  firstName: string;
  lastName: string;
  doctorPublicId: string;
  specialization: string;
}
