/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ConsultationDetailDto } from "./ConsultationDetailDto";
import type { LocalDate } from "./LocalDate";
import type { LocalTime } from "./LocalTime";
import type { Symptom } from "./Symptom";

export interface DoctorAppointmentDetailDto {
  publicId?: string;
  slug?: string;
  visitReason?: string;
  patientName?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  patientAge?: number | string;
  patientGender?: string;
  date?: LocalDate;
  startTime?: LocalTime;
  endTime?: LocalTime;
  status?: string;
  statusColorCode?: string;
  /** @nullable */
  symptoms?: Symptom[] | null;
  consultation?: null | ConsultationDetailDto;
}
