/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AllergyDto } from './AllergyDto';
import type { EmergencyContactDto } from './EmergencyContactDto';
import type { LocalDate } from './LocalDate';

export interface DoctorPatientDto {
  patientPublicId?: string;
  fullName?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  age?: number | string;
  gender?: string;
  /** @nullable */
  bloodGroup?: string | null;
  /** @nullable */
  phone?: string | null;
  allergies?: AllergyDto[];
  emergencyContact?: null | EmergencyContactDto;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalAppointments?: number | string;
  lastVisitDate?: null | LocalDate;
}
