/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface EmergencyContactDto {
  name: string;
  relationship: string;
  phone: string;
}
