/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type GetAllAppointmentsForReceptionistParams = {
  View?: string;
  Status?: string;
  Search?: string;
  DoctorId?: string;
  From?: string;
  To?: string;
  /**
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  Page?: number | string;
  /**
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  PageSize?: number | string;
  SortOrder?: string;
};
