/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LocalDate } from "./LocalDate";

export interface GetMeResponse {
  publicId: string;
  email: string;
  firstName: string;
  lastName: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
  /** @nullable */
  phone: string | null;
  icNumber: string;
  dateOfBirth: LocalDate;
  /** @nullable */
  gender: string | null;
  /** @nullable */
  addressLine1: string | null;
  /** @nullable */
  addressLine2: string | null;
  /** @nullable */
  city: string | null;
  /** @nullable */
  state: string | null;
  /** @nullable */
  postalCode: string | null;
  /** @nullable */
  country: string | null;
  roles: string[];
}
