/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface LabReportStatusDto {
  slug: string;
  name: string;
  /** @nullable */
  colorCode: string | null;
}
