/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Instant } from "./Instant";
import type { LabReportStatusDto } from "./LabReportStatusDto";

export interface LabReportDto {
  publicId: string;
  slug: string;
  reportType: string;
  /** @nullable */
  fileName: string | null;
  patientPublicId: string;
  patientFullName: string;
  /** @nullable */
  consultationPublicId: string | null;
  status: LabReportStatusDto;
  uploadedAt: null | Instant;
  createdAt: Instant;
}
