/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AdminLabTechDto } from './AdminLabTechDto';

export interface PagedResultOfAdminLabTechDto {
  items: AdminLabTechDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalPages?: number | string;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
}
