/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DoctorListDto } from './DoctorListDto';

export interface PagedResultOfDoctorListDto {
  items: DoctorListDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalPages?: number | string;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
}
