/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PrescriptionInstructionsRequest } from './PrescriptionInstructionsRequest';

export interface PrescriptionRequest {
  medicationName: string;
  dosage: string;
  frequency: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  durationDays: number | string;
  instructions: PrescriptionInstructionsRequest;
}
