/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LocalDate } from './LocalDate';
import type { LocalTime } from './LocalTime';

export interface ReceptionistAppointmentDto {
  patientName?: string;
  doctorName?: string;
  /** @nullable */
  doctorAvatarUrl?: string | null;
  specialization?: string;
  status?: string;
  statusSlug?: string;
  statusColorCode?: string;
  /** @nullable */
  patientAvatarUrl?: string | null;
  date?: LocalDate;
  startTime?: LocalTime;
  endTime?: LocalTime;
  publicId?: string;
  slug: string;
  visitReason: string;
}
