/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LocalDate } from "./LocalDate";
import type { LocalTime } from "./LocalTime";
import type { Symptom } from "./Symptom";

export interface ReceptionistAppointmentDetailDto {
  publicId?: string;
  slug?: string;
  visitReason?: string;
  /** @nullable */
  cancellationReason?: string | null;
  patientName?: string;
  /** @nullable */
  patientAvatarUrl?: string | null;
  doctorPublicId?: string;
  doctorName?: string;
  /** @nullable */
  doctorAvatarUrl?: string | null;
  specialization?: string;
  schedulePublicId?: string;
  date?: LocalDate;
  startTime?: LocalTime;
  endTime?: LocalTime;
  status?: string;
  statusSlug?: string;
  statusColorCode?: string;
  /** @nullable */
  symptoms?: Symptom[] | null;
}
