/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Allergy } from "./Allergy";
import type { EmergencyContact } from "./EmergencyContact";
import type { LocalDate } from "./LocalDate";

export interface ReceptionistPatientsDto {
  userPublicId?: string;
  patientPublicId?: string;
  slug?: string;
  lastName?: string;
  firstName?: string;
  /** @nullable */
  avatarUrl?: string | null;
  patientEmail?: string;
  dateOfBirth?: LocalDate;
  phoneNumber?: string;
  icNumber?: string;
  bloodGroup?: string;
  /** @nullable */
  allergies?: Allergy[] | null;
  /** @nullable */
  emergencyContacts?: EmergencyContact[] | null;
}
