/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ReceptionistPatientAppointmentDto } from "./ReceptionistPatientAppointmentDto";

export interface ReceptionistPatientHistoryResponse {
  patientName?: string;
  items?: ReceptionistPatientAppointmentDto[];
}
