/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LocalDate } from './LocalDate';
import type { PrescriptionRequest } from './PrescriptionRequest';

export interface SubmitConsultationRequest {
  subjective: string;
  objective: string;
  assessment: string;
  plan: string;
  followUpDate: null | LocalDate;
  prescriptions: PrescriptionRequest[];
}
