/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LocalDate } from './LocalDate';
import type { UpdateDoctorAddressCommand } from './UpdateDoctorAddressCommand';
import type { UpdateDoctorQualificationCommand } from './UpdateDoctorQualificationCommand';

export interface UpdateDoctorCommand {
  firstName: string;
  lastName: string;
  username: string;
  email: string;
  /** @nullable */
  phoneNumber: string | null;
  gender: string;
  dateOfBirth: LocalDate;
  /** @nullable */
  bio: string | null;
  specialization: string;
  licenseNumber: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$
     */
  consultationFee: number | string | null;
  departmentName: string;
  address: null | UpdateDoctorAddressCommand;
  qualifications: UpdateDoctorQualificationCommand[];
}
