/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateDoctorAddressCommand {
  street: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
}
