/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateProfileCommand {
  firstName: string;
  lastName: string;
  /** @nullable */
  phone: string | null;
  icNumber: string;
  /** @nullable */
  address: string | null;
}
