/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LocalDate } from './LocalDate';

export interface UpdateProfileCommand {
  firstName: string;
  lastName: string;
  /** @nullable */
  phone: string | null;
  icNumber: string;
  /** @nullable */
  address: string | null;
  /** @nullable */
  username: string | null;
  dateOfBirth: null | LocalDate;
  /** @nullable */
  gender: string | null;
  /** @nullable */
  addressLine1: string | null;
  /** @nullable */
  addressLine2: string | null;
  /** @nullable */
  city: string | null;
  /** @nullable */
  state: string | null;
  /** @nullable */
  postalCode: string | null;
  /** @nullable */
  country: string | null;
}
