/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Allergy } from './Allergy';
import type { EmergencyContact } from './EmergencyContact';

export interface UpdateMedicalRecordCommand {
  bloodGroup: string;
  emergencyContact: null | EmergencyContact;
  allergies: Allergy[];
}
