/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * TeleHealth.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Allergy } from './Allergy';
import type { EmergencyContact } from './EmergencyContact';
import type { LocalDate } from './LocalDate';

export interface UpdatePatientRecordCommand {
  firstName: string;
  lastName: string;
  dateOfBirth: LocalDate;
  /** @nullable */
  phoneNumber: string | null;
  /**
     * @minLength 1
     * @maxLength 1
     */
  gender: string;
  /** @nullable */
  bloodGroup: string | null;
  emergencyContact: null | EmergencyContact;
  allergies: Allergy[];
}
