/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedSchedulesRouteImport } from './routes/_protected/schedules'
import { Route as ProtectedReceptionistsRouteImport } from './routes/_protected/receptionists'
import { Route as ProtectedPatientsRouteImport } from './routes/_protected/patients_'
import { Route as ProtectedLabReportsRouteImport } from './routes/_protected/lab-reports_'
import { Route as ProtectedDoctorsRouteImport } from './routes/_protected/doctors'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedAppointmentsRouteImport } from './routes/_protected/appointments_'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedPatientsIdRouteImport } from './routes/_protected/patients.$id'
import { Route as ProtectedAppointmentsBookRouteImport } from './routes/_protected/appointments.book'
import { Route as ProtectedAppointmentsIdRouteImport } from './routes/_protected/appointments.$id'
import { Route as ProtectedPatientsIdMedicalProfileRouteImport } from './routes/_protected/patients.$id.medical-profile'
import { Route as ProtectedPatientsIdHistoryRouteImport } from './routes/_protected/patients.$id.history'
import { Route as ProtectedAppointmentsEditIdRouteImport } from './routes/_protected/appointments.edit.$id'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSchedulesRoute = ProtectedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReceptionistsRoute = ProtectedReceptionistsRouteImport.update({
  id: '/receptionists',
  path: '/receptionists',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPatientsRoute = ProtectedPatientsRouteImport.update({
  id: '/patients_',
  path: '/patients',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLabReportsRoute = ProtectedLabReportsRouteImport.update({
  id: '/lab-reports_',
  path: '/lab-reports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDoctorsRoute = ProtectedDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppointmentsRoute = ProtectedAppointmentsRouteImport.update({
  id: '/appointments_',
  path: '/appointments',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedPatientsIdRoute = ProtectedPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAppointmentsBookRoute =
  ProtectedAppointmentsBookRouteImport.update({
    id: '/appointments/book',
    path: '/appointments/book',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAppointmentsIdRoute = ProtectedAppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPatientsIdMedicalProfileRoute =
  ProtectedPatientsIdMedicalProfileRouteImport.update({
    id: '/medical-profile',
    path: '/medical-profile',
    getParentRoute: () => ProtectedPatientsIdRoute,
  } as any)
const ProtectedPatientsIdHistoryRoute =
  ProtectedPatientsIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ProtectedPatientsIdRoute,
  } as any)
const ProtectedAppointmentsEditIdRoute =
  ProtectedAppointmentsEditIdRouteImport.update({
    id: '/appointments/edit/$id',
    path: '/appointments/edit/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/appointments': typeof ProtectedAppointmentsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/doctors': typeof ProtectedDoctorsRoute
  '/lab-reports': typeof ProtectedLabReportsRoute
  '/patients': typeof ProtectedPatientsRoute
  '/receptionists': typeof ProtectedReceptionistsRoute
  '/schedules': typeof ProtectedSchedulesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/appointments/$id': typeof ProtectedAppointmentsIdRoute
  '/appointments/book': typeof ProtectedAppointmentsBookRoute
  '/patients/$id': typeof ProtectedPatientsIdRouteWithChildren
  '/appointments/edit/$id': typeof ProtectedAppointmentsEditIdRoute
  '/patients/$id/history': typeof ProtectedPatientsIdHistoryRoute
  '/patients/$id/medical-profile': typeof ProtectedPatientsIdMedicalProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/appointments': typeof ProtectedAppointmentsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/doctors': typeof ProtectedDoctorsRoute
  '/lab-reports': typeof ProtectedLabReportsRoute
  '/patients': typeof ProtectedPatientsRoute
  '/receptionists': typeof ProtectedReceptionistsRoute
  '/schedules': typeof ProtectedSchedulesRoute
  '/settings': typeof ProtectedSettingsRoute
  '/appointments/$id': typeof ProtectedAppointmentsIdRoute
  '/appointments/book': typeof ProtectedAppointmentsBookRoute
  '/patients/$id': typeof ProtectedPatientsIdRouteWithChildren
  '/appointments/edit/$id': typeof ProtectedAppointmentsEditIdRoute
  '/patients/$id/history': typeof ProtectedPatientsIdHistoryRoute
  '/patients/$id/medical-profile': typeof ProtectedPatientsIdMedicalProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_protected/appointments_': typeof ProtectedAppointmentsRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/doctors': typeof ProtectedDoctorsRoute
  '/_protected/lab-reports_': typeof ProtectedLabReportsRoute
  '/_protected/patients_': typeof ProtectedPatientsRoute
  '/_protected/receptionists': typeof ProtectedReceptionistsRoute
  '/_protected/schedules': typeof ProtectedSchedulesRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/appointments/$id': typeof ProtectedAppointmentsIdRoute
  '/_protected/appointments/book': typeof ProtectedAppointmentsBookRoute
  '/_protected/patients/$id': typeof ProtectedPatientsIdRouteWithChildren
  '/_protected/appointments/edit/$id': typeof ProtectedAppointmentsEditIdRoute
  '/_protected/patients/$id/history': typeof ProtectedPatientsIdHistoryRoute
  '/_protected/patients/$id/medical-profile': typeof ProtectedPatientsIdMedicalProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/appointments'
    | '/dashboard'
    | '/doctors'
    | '/lab-reports'
    | '/patients'
    | '/receptionists'
    | '/schedules'
    | '/settings'
    | '/appointments/$id'
    | '/appointments/book'
    | '/patients/$id'
    | '/appointments/edit/$id'
    | '/patients/$id/history'
    | '/patients/$id/medical-profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/appointments'
    | '/dashboard'
    | '/doctors'
    | '/lab-reports'
    | '/patients'
    | '/receptionists'
    | '/schedules'
    | '/settings'
    | '/appointments/$id'
    | '/appointments/book'
    | '/patients/$id'
    | '/appointments/edit/$id'
    | '/patients/$id/history'
    | '/patients/$id/medical-profile'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/appointments_'
    | '/_protected/dashboard'
    | '/_protected/doctors'
    | '/_protected/lab-reports_'
    | '/_protected/patients_'
    | '/_protected/receptionists'
    | '/_protected/schedules'
    | '/_protected/settings'
    | '/_protected/appointments/$id'
    | '/_protected/appointments/book'
    | '/_protected/patients/$id'
    | '/_protected/appointments/edit/$id'
    | '/_protected/patients/$id/history'
    | '/_protected/patients/$id/medical-profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/schedules': {
      id: '/_protected/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof ProtectedSchedulesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/receptionists': {
      id: '/_protected/receptionists'
      path: '/receptionists'
      fullPath: '/receptionists'
      preLoaderRoute: typeof ProtectedReceptionistsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/patients_': {
      id: '/_protected/patients_'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof ProtectedPatientsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/lab-reports_': {
      id: '/_protected/lab-reports_'
      path: '/lab-reports'
      fullPath: '/lab-reports'
      preLoaderRoute: typeof ProtectedLabReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/doctors': {
      id: '/_protected/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof ProtectedDoctorsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/appointments_': {
      id: '/_protected/appointments_'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof ProtectedAppointmentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/patients/$id': {
      id: '/_protected/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof ProtectedPatientsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/appointments/book': {
      id: '/_protected/appointments/book'
      path: '/appointments/book'
      fullPath: '/appointments/book'
      preLoaderRoute: typeof ProtectedAppointmentsBookRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/appointments/$id': {
      id: '/_protected/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/appointments/$id'
      preLoaderRoute: typeof ProtectedAppointmentsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/patients/$id/medical-profile': {
      id: '/_protected/patients/$id/medical-profile'
      path: '/medical-profile'
      fullPath: '/patients/$id/medical-profile'
      preLoaderRoute: typeof ProtectedPatientsIdMedicalProfileRouteImport
      parentRoute: typeof ProtectedPatientsIdRoute
    }
    '/_protected/patients/$id/history': {
      id: '/_protected/patients/$id/history'
      path: '/history'
      fullPath: '/patients/$id/history'
      preLoaderRoute: typeof ProtectedPatientsIdHistoryRouteImport
      parentRoute: typeof ProtectedPatientsIdRoute
    }
    '/_protected/appointments/edit/$id': {
      id: '/_protected/appointments/edit/$id'
      path: '/appointments/edit/$id'
      fullPath: '/appointments/edit/$id'
      preLoaderRoute: typeof ProtectedAppointmentsEditIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedPatientsIdRouteChildren {
  ProtectedPatientsIdHistoryRoute: typeof ProtectedPatientsIdHistoryRoute
  ProtectedPatientsIdMedicalProfileRoute: typeof ProtectedPatientsIdMedicalProfileRoute
}

const ProtectedPatientsIdRouteChildren: ProtectedPatientsIdRouteChildren = {
  ProtectedPatientsIdHistoryRoute: ProtectedPatientsIdHistoryRoute,
  ProtectedPatientsIdMedicalProfileRoute:
    ProtectedPatientsIdMedicalProfileRoute,
}

const ProtectedPatientsIdRouteWithChildren =
  ProtectedPatientsIdRoute._addFileChildren(ProtectedPatientsIdRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAppointmentsRoute: typeof ProtectedAppointmentsRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedDoctorsRoute: typeof ProtectedDoctorsRoute
  ProtectedLabReportsRoute: typeof ProtectedLabReportsRoute
  ProtectedPatientsRoute: typeof ProtectedPatientsRoute
  ProtectedReceptionistsRoute: typeof ProtectedReceptionistsRoute
  ProtectedSchedulesRoute: typeof ProtectedSchedulesRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedAppointmentsIdRoute: typeof ProtectedAppointmentsIdRoute
  ProtectedAppointmentsBookRoute: typeof ProtectedAppointmentsBookRoute
  ProtectedPatientsIdRoute: typeof ProtectedPatientsIdRouteWithChildren
  ProtectedAppointmentsEditIdRoute: typeof ProtectedAppointmentsEditIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAppointmentsRoute: ProtectedAppointmentsRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedDoctorsRoute: ProtectedDoctorsRoute,
  ProtectedLabReportsRoute: ProtectedLabReportsRoute,
  ProtectedPatientsRoute: ProtectedPatientsRoute,
  ProtectedReceptionistsRoute: ProtectedReceptionistsRoute,
  ProtectedSchedulesRoute: ProtectedSchedulesRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedAppointmentsIdRoute: ProtectedAppointmentsIdRoute,
  ProtectedAppointmentsBookRoute: ProtectedAppointmentsBookRoute,
  ProtectedPatientsIdRoute: ProtectedPatientsIdRouteWithChildren,
  ProtectedAppointmentsEditIdRoute: ProtectedAppointmentsEditIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
